# ──────────────────────────────────────────────────────────────────────
#  cloudbuild.yaml — Google Cloud Build CI/CD pipeline
#  Fixed: Uses SHORT_SHA instead of COMMIT_SHA (works for manual triggers)
#         and tags image with 'latest' only on direct console deploys.
# ──────────────────────────────────────────────────────────────────────

substitutions:
  _SERVICE_NAME: edushield-ai     # Cloud Run service name
  _REGION: asia-south1            # Mumbai region — closest to India
  _REPO: edushield-repo           # Artifact Registry repository name

steps:
  # ── STEP 1: Build the Docker image ─────────────────────────────────
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--no-cache"
      - "-f"
      - "Dockerfile"
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE_NAME}:$SHORT_SHA"
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE_NAME}:latest"
      - "."

  # ── STEP 2: Push both tags to Artifact Registry ────────────────────
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "--all-tags"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE_NAME}"

  # ── STEP 3: Deploy the new image to Cloud Run ──────────────────────
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "${_SERVICE_NAME}"
      - "--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE_NAME}:latest"
      - "--region=${_REGION}"
      - "--platform=managed"
      - "--allow-unauthenticated"
      - "--memory=512Mi"
      - "--cpu=1"
      - "--min-instances=0"
      - "--max-instances=5"
      - "--concurrency=80"
      - "--timeout=60"
      - "--port=8080"

images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE_NAME}:$SHORT_SHA"
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE_NAME}:latest"

options:
  logging: CLOUD_LOGGING_ONLY
